{% set name = "xhydro" %}
{% set version = "0.6.1" %}
{% set python_min = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xhydro-{{ version }}.tar.gz
  sha256: 98b0fe17fbe2639bae94ec980af936f356d51da3ceb3fb468717f17bf078eed2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.23.0
    - dask
    - dask-geopandas
    - geopandas >=1.0
    - haversine >=2.8.1
    - leafmap
    - mapclassify  # Hidden dependency needed to extract watershed delineation using leafmap objects
    - numpy >=1.24
    - pandas >=2.2
    - planetary-computer
    - pooch >=1.8.0
    - pystac >=1.12.0
    - pystac-client
    - pyyaml >=6.0.2
    - rasterio
    - ravenpy >=0.18.1
    - rioxarray >=0.15.0
    - spotpy >=1.6.2
    - stackstac >=0.5.1
    - statsmodels >=0.14.0
    - tqdm
    - xarray >=2023.11.0
    - xarray-spatial >=0.3.7
    - xclim
    - xscen >=0.12.1,<0.14
    - xvec
  run_constrained:
    - xdatasets >=0.3.8

test:
  imports:
    - xhydro
  commands:
    # - pip check # PyCRS gives a false positive here
    - pytest tests
  requires:
    - python {{ python_min }}
    - pip
    - lmoments3  # needed for test_regional.py
    - pytest >=8.3.2
    - pytest-xdist >=3.2.0
    - xdatasets >=0.3.8  # needed for test_gis.py
  source_files:
    - CHANGELOG.rst
    - pyproject.toml
    - tests

about:
  home: https://github.com/hydrologie/xdatasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hydrological analysis library built with xarray.
  dev_url: https://github.com/hydrologie/xhydro
  doc_url: https://xhydro.readthedocs.io

extra:
  recipe-maintainers:
    - RondeauG
    - sebastienlanglois
    - Zeitsperre
